Ajout du workflow pour éxécuter make
George-Ober/kholles pull request #22
Opened 2024-11-25 23:27 UTC by Hugo-Vangilluwen

2024-11-25 23:45 UTC, 3fxcf9 requested changes

2024-11-25 23:45 UTC, 3fxcf9 commented on .github/workflow/make.yml
> +      run: make
Il faut installer pdflatex et tous les packages utilisés avant d'executer make. Peut-être qu'un
```
run: sudo apt-get update && sudo apt-get install -y texlive-full
```
suffit.

2024-11-25 23:45 UTC, 3fxcf9 commented on CONTRIBUER.md
> +Nous sommes peu à écrire les questions de khôlles alors *merci beaucoup* de contribuer. Tu peux simplement nous faire remarquer les fautes d'autographe, les raisonnements trop rapides, des idées pour
Je me demande si c'est fait exprès mais si jamais : autographe -> orthographe

2024-11-25 23:45 UTC, 3fxcf9 commented on CONTRIBUER.md
> +Simplement, commence votre document LaTeX par
Je ne comprends pas cette modification. « commencez votre document » me semble correct.

2024-11-26 11:13 UTC, Hugo-Vangilluwen commented on CONTRIBUER.md
> +Nous sommes peu à écrire les questions de khôlles alors *merci beaucoup* de contribuer. Tu peux simplement nous faire remarquer les fautes d'autographe, les raisonnements trop rapides, des idées pour
C'est une erreur, c'était pas voulu.

2024-11-26 11:14 UTC, Hugo-Vangilluwen commented on CONTRIBUER.md
> +Simplement, commence votre document LaTeX par
Je voulais tutoyer les contributeurs plutôt que les vouvoyer mais j'ai oublié de changer 'votre'.

2024-11-26 19:08 UTC, Hugo-Vangilluwen commented on .github/workflow/make.yml
> +      run: make
J'ai jeté un coup d'œil à HoTT et c'est ce qu'il font.

```yaml
run:
  - name: Install texlive-full
    step: |
      apt update
      apt install texlive-full
```

La barre verticale | permet de mettre des commandes sur plusieurs lignes pour être plus propre.

2024-12-01 13:57 UTC, 3fxcf9 approved these changes

2024-12-01 13:57 UTC, merged